version: 1.0

remoter:
  host: localhost
  port: 9003

database:
  sqlite_db: storage_challenge.sqlite
  max_idle_conns: 3
  max_open_conns: 10
  debug: true

masternode_id: jXTwS1eCNDopMUIZAQnvpGlVe9lEnbauoh8TNDRoZcRTJVxCmZu1oSySBM1UwwyHDh7npbn01tZG0q2xyGmVJr
