version: 1.0

remoter:
  host: 0.0.0.0
  port: 9000

database:
  dbms: sqlite
  dsn: storage-challenge.sqlite
  max_idle_conns: 3
  max_open_conns: 10
  debug: false

masternode_id: jXoIquQRCdRrnjOClioRrSdG6pGyqG3audIQrVwIc6OgR3FFa90WemZ1xuylKjUBMj3gZpL69GT2fdJV99jB81
