version: 1.0

remoter:
  host: localhost
  port: 9001

database:
  dbms: sqlite
  dsn: storage-challenge.sqlite
  max_idle_conns: 3
  max_open_conns: 10
  debug: true

# test node0
# masternode_id: jXlzy0y3L1gYG04DBEZSKI9KV5BReiRzrW5bDBls3M2gtS6R0Ed8MHrEW9hzzgi4aW1taxNzChPSHEgJY4aTbw
# test node1
masternode_id: jXEZVtIEVmSkYw0v8qGjsBrrELBOPuedNYMctelLWSlw6tiVNljFMpZFir30SN9r645tEAKwEAYfKR3o4Ek5YM
masternode_passphrase: example_passphrase
