folder_path_containing_sample_raptorq_symbol_files: "D:\\je_golang_storage_challenge_code\\sample_raptorq_symbol_files\\"
rqsymbol_file_storage_data_folder_path: "D:\\je_golang_storage_challenge_code\\rqsymbol_files_stored_by_masternodes\\"
new_rqsymbol_file_storage_data_folder_path: "D:\\je_golang_storage_challenge_code\\incremental_raptorq_symbol_files\\"
max_seconds_to_respond_to_storage_challenge: 10
number_of_challenge_replicas: 5
slice_of_pastel_masternode_ids:
  - jX2Oo9VqcP4hPOTNJVC5eGqnY5tXNoSdDdHEIuKcaUQ6VKw68CGmqhG9FWb5XU67YAzVMtDf9Io8HLfVpCp1Pc
  - jXS9NIXHj8pd9mLNsP2uKgIh1b3EH2aq5dwupUF7hoaltTE8Zlf6R7Pke0cGr071kxYxqXHQmfVO5dA4jH0ejQ
  - jX8oThrVrg0ZYhz3qXzv698LZOy2QG33R9w4eXTzKzCKBEWW9TU6R13TnjxDJAshEsWxFkRE0pPwoIvPEJJu6I
  - jX6K2iP24sWtyU9wCnE99emxbz4QxCk2n43WfRuBweYTVvv0AencLFhXwUUu33G1siQIE3LQaiZh2ZSxgGcHEG
  - jXRXfG5kV1FYWKABT88mupZaDm6LCMgHUGtMjRYgYG1AYxvWk5hkTDRBov4H2Ksn0USNxGuX61c4OYbP9uqg4I
  - jXOvtvYxXUMCc83kWWvdOwUk4do4PCeRHcONECxu9TMwpqJ6l0b5fkUCby4AKBUEumt5tzWrytAoGgZBRL6WHq
  - jXxveMgUk0VrYSYOD3Pt4Vqo2GtPMfWW6NO6WUpieKcT1PGeeXDk4TSqifIGumxRvQE5YuJDzXlYmHISgljt98
  - jXEZVtIEVmSkYw0v8qGjsBrrELBOPuedNYMctelLWSlw6tiVNljFMpZFir30SN9r645tEAKwEAYfKR3o4Ek5YM
  - jXVmx86fiMALiMr1HwkcS6fLpdHZkIRxZ111wPyfuZtrmqtaupxg5EVV2HNgEW71tzrCQoAS0lOV35mpqAqvsE
  - jXYiHNqO9B7psxFQZb1thEgDNykZjL8GkHMZNPZx3iCYre1j3g0zHynlTQ9TdvY6dcRlYIsNfwIQ6nVXBSVJis
  - jXpDb5K6S81ghCusMOXLP6k0RvqgFhkBJSFf6OhjEmpvCWGZiptRyRgfQ9cTD709sA58m5czpipFnvpoHuPX0F
  - jXqBzHsk8P1cuRFrsRkQR5IhPzwFyCxE369KYqFLSITr8l5koLWcabZZDUVltIJ8666bE53G5fbtCz4veU2FCP
  - jX4E9LLzsP3Q8lVbT8QxFsgKf1ggDAKaC9EJoM1CvNFlhD81NmgpFLjCcQhP99UvheIid7NwYDQR9QvzRrwuSA
  - jXLzzFEMzls4IpwFpN1QC5mQFFhACgH1A3jRCkZ1OE3s0gxOndMtdFI9UOFkIzTDOTl6omYThNOFcbz3ajqYX4
  - jXdDgE3szIzRHzXUJZBlk8f097Peqje7Kz92vzsDuCtNDHLJxw2dqQZRlQXTGjpR2pw13Rpct3xe0XFhFJlNuv
  - jX5jep6veu2fvSR9CJbCAsi1Y0g6SuOV1p7GVTf1BOWwvyfs0hsO7ZxA9eqWsjrVbdg80IjCFlhBrFF8EHqFFa
  - jXNtmNRYVQoRCZK3BURcJ1mqusS856p9OX4eZH8iTPhDaFPV2OiTf875JzAwZs1sbIbQSYCrBFstUP4FNTheBb
  - jXTqmW8sZgDbCnNNdhAqoBBDyP5zHD2VK2fw4FURPyi7oDx0w41Ifb0RA0ny3hvTvQHcOnFdmiyqHE5Sp3gbIa
  - jXljm8vYKP41PCXixn7pHge75nuPy7sVLiwvNTwvMv4QHBAoUvnpXTNJOwGJNlEqKViLqe5qrjJ95Oj1qg4xtv
  - jXzriQGf1FY5GOy7vyA0tOUUscfwugzUutPL5NyFuhCIeYNd7AAbsHxdnSS8Pgxoxd4hU6e16sWI6gh0CpegZv
  - jXTwS1eCNDopMUIZAQnvpGlVe9lEnbauoh8TNDRoZcRTJVxCmZu1oSySBM1UwwyHDh7npbn01tZG0q2xyGmVJr
  - jXl8wiIuix4QxZsdhtnxye7bJn5z1M3yBEw0JxsB8vAb3Yb6VCrfHH3al8iCvcJjQTVdsMOCppEfVfk0TgfQ5r
  - jXD8SVytGpv7qDzCY0rjUNE2gi24jLpdihupm5pD7u1plOBL6fB7zFIddA8ezubp0Bl2dnxfptQSFhdCOYwqq2
  - jXIC54zVCSUqITW3bAZw5rvu2lUwl5c9qMeI1hxm3VRBlYG7v71aGRTX55JbVonKsk80DdCv23VSLiKq2ao3V7
  - jXlzy0y3L1gYG04DBEZSKI9KV5BReiRzrW5bDBls3M2gtS6R0Ed8MHrEW9hzzgi4aW1taxNzChPSHEgJY4aTbw
slice_of_new_pastel_masternode_ids:
  - jXcTnItjgB14tyS7Yf42nuVGbENWIAkEuTc5uFLKAkrBzw83hpSz81JarDL5q0dDl1CwoMFduhTI9MKiQBftCn
  - jXouSob7xRPUrmkN2Pz5l47pjxPakzvIcjGHNCbpJu0FnGDmLtgqkyyVT1yns0YoywHpn1QHVtf6nEIDq81kRK
  - jXP2TbWi6FSo1fhNi0Y7MAycSKIYYOqoyXJpPubwofiBVpt5pDcIbHD11mTHCZFfWUbkiW8Lw98OOw9s09d8bV
  - jX4ZyVARb6nffYxnKW65S163zk9KnIP5uMZZiCQqLOUgCcIygGlYQwA44xgGwGYhOIzaHs9aeupXTZ5CxzNkwv
  - jXdBoCJv34Kxlt5becK2Zo1SPxDahF1FNw6FOAjClisZAN5CzbrNfhqbJZdh8mvPfmqMvYUV4ibefmc8v1O9lb
  - jXWvtom4YSi5ryysN75E4XIJmCpNijUwNbWgDQno0XlLrnxV1yeB1QEA5s0NnDu0B86H6Pw2zdLBWYq6f8J5zt
  - jX6Sx7XSDC5k7eM1WVek7TOyJyNgjOIENuwrq4k3gvMikZd7XP00UqHz9fWpB6iBjf9o1B4UykPkEXZ4qb94Mo
  - jXOUqQCY9F87XNuIplL7rx5rfsyxLs2d8MIcvJEINxh85YY3ci1n4R6u5loFG9hnukKqqk9x89cv8VR7FR97mx
  - jXc3Id8q6G1KzcraKDl85qcz0sOlkhND2T8DrCK08EXuT99UHu8E6un0GN8Hhil917tXBct3ZCPcASd05M97a3
  - jXqO74TE9UuVkOmBxbmFY7NlGXbRc9IeAxv34I1WtHfx7zsRreT4jRfaFdhYsQdCksFtFlHGOQ3QQ2qyeHCmiB
  - jXrjVoNRTvNKv5LlYeiC7Y4qu6rdEAKndJfU76tX0gQHSmUuAs2aohzeRRuOB9wKsOLazlCVWPomJYIxCSeKsN
  - jXxtDUZETq7S7L013AIybkSgiE2GUzEZyfxnZXhu3Bw6wIy3rtx4AMdqnGbAO63M4zLQX2s6do6l7vD0xNlAME
  - jXHOrWYNA7G0K9gl6jZps23YjsD76V324bF47owQVoYw2JcRtWaAeEfAmIuxClNJtJ9Ttd1yN8PKlS3YnrGfh9
  - jXZwKfMqhJJjEyghWBLOQdJozQyCNhI2K42Ie5bhKh3RQfbpvwyYltICqKhE1z0RhUniqTBpFp8uSZsGPIOhM8
  - jXMR9pP8eaywrDKVpunUk0X9jJjt5BHiMIaXxLOA0DYfk7PssnqXFf2cjEnWJJzJ9Q0wH6D4DuEOT3CBXedmlT
  - jXyzkE0afpAOQJ0e1teG6Xaayfb3gTt4LwOW0P4t3fuRIWvLwegX6xuFyD5TiSYvxYZEd5D9lwO7eiGj6Ud7ZM
  - jXg9aVvEjTv2BXDhEJiyf7MCghyrOsyDdipLWLImh5CFWgfvd4GV8smfRO0Hxm2c0cRy28rLDWX43j8J2uzDQO
  - jXIGc0SbVWHFRKemuDSpkTIrCybP3tFbT2c5LOZZuKgBZf95eFZ62QkBP4mmFoZrQkVB0bmn70Oran3vg5fW1X
  - jXhORx7pRxBlZpFPHeG39CtjVuCryfJbPsVJfLhGW5gdGJ0R86Jo8P3lDjcbATPYeq1K8pKjDmfoVBTIU6Z3AF
  - jXYmZTKDH2RTGbw7s5o6RbMrLh4EpxVOGaisOf7I29pCMRHlynAUrbmkbcvsgJscPHFFO9YNu5vvwxWQmW4A0Z