version: 1.0

remoter:
  host: localhost
  port: 9001

database:
  sqlite_db: storage-challenge.sqlite
  max_idle_conns: 3
  max_open_conns: 10
  debug: true

masternode_id: jXEZVtIEVmSkYw0v8qGjsBrrELBOPuedNYMctelLWSlw6tiVNljFMpZFir30SN9r645tEAKwEAYfKR3o4Ek5YM
