version: 1

remoter:
  host: 0.0.0.0
  port: 9000

database:
  dbms: sqlite
  dsn: storage-challenge.sqlite
  max_idle_conns: 3
  max_open_conns: 10
  debug: false

masternode_id: jXlzy0y3L1gYG04DBEZSKI9KV5BReiRzrW5bDBls3M2gtS6R0Ed8MHrEW9hzzgi4aW1taxNzChPSHEgJY4aTbw
