migrate:
	STORAGE_CHALLENGE_CONFIG=node0 ./storage-challenges --migrate-seed Enter

start-node0:
	# node0
	STORAGE_CHALLENGE_CONFIG=node0 ./storage-challenges
  
start-node1:
	# node1
	STORAGE_CHALLENGE_CONFIG=node1 ./storage-challenges

start-node2:
	# node2
	STORAGE_CHALLENGE_CONFIG=node2 ./storage-challenges

start-node3:
	# node3
	STORAGE_CHALLENGE_CONFIG=node3 ./storage-challenges
